cmake3 .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/vagrant  -DBUILD_DISTRIBUTABLE_LIBRARY=True -DOPENSSL_ROOT_DIR=/usr/local/openssl -DBUILD_JAVA=1 -DPROTOBUF_LIBRARY=$PROTOBUF_LIBRARY
